# Generated by Django 5.1.4 on 2025-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebase',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
