# Generated by Django 5.1.4 on 2025-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_downloadapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadapp',
            name='info',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
